// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Game.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_Game_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_Game_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3011000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3011004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_Game_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_Game_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[6]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_Game_2eproto;
namespace Game {
class ClientMessage;
class ClientMessageDefaultTypeInternal;
extern ClientMessageDefaultTypeInternal _ClientMessage_default_instance_;
class Inventory;
class InventoryDefaultTypeInternal;
extern InventoryDefaultTypeInternal _Inventory_default_instance_;
class Object;
class ObjectDefaultTypeInternal;
extern ObjectDefaultTypeInternal _Object_default_instance_;
class Score;
class ScoreDefaultTypeInternal;
extern ScoreDefaultTypeInternal _Score_default_instance_;
class ServerMessage;
class ServerMessageDefaultTypeInternal;
extern ServerMessageDefaultTypeInternal _ServerMessage_default_instance_;
class Vector3;
class Vector3DefaultTypeInternal;
extern Vector3DefaultTypeInternal _Vector3_default_instance_;
}  // namespace Game
PROTOBUF_NAMESPACE_OPEN
template<> ::Game::ClientMessage* Arena::CreateMaybeMessage<::Game::ClientMessage>(Arena*);
template<> ::Game::Inventory* Arena::CreateMaybeMessage<::Game::Inventory>(Arena*);
template<> ::Game::Object* Arena::CreateMaybeMessage<::Game::Object>(Arena*);
template<> ::Game::Score* Arena::CreateMaybeMessage<::Game::Score>(Arena*);
template<> ::Game::ServerMessage* Arena::CreateMaybeMessage<::Game::ServerMessage>(Arena*);
template<> ::Game::Vector3* Arena::CreateMaybeMessage<::Game::Vector3>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace Game {

enum Net : int {
  PING = 0,
  PONG = 1
};
bool Net_IsValid(int value);
constexpr Net Net_MIN = PING;
constexpr Net Net_MAX = PONG;
constexpr int Net_ARRAYSIZE = Net_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* Net_descriptor();
template<typename T>
inline const std::string& Net_Name(T enum_t_value) {
  static_assert(::std::is_same<T, Net>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function Net_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    Net_descriptor(), enum_t_value);
}
inline bool Net_Parse(
    const std::string& name, Net* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<Net>(
    Net_descriptor(), name, value);
}
enum Direction : int {
  UP = 0,
  DOWN = 1,
  LEFT = 2,
  RIGHT = 3
};
bool Direction_IsValid(int value);
constexpr Direction Direction_MIN = UP;
constexpr Direction Direction_MAX = RIGHT;
constexpr int Direction_ARRAYSIZE = Direction_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* Direction_descriptor();
template<typename T>
inline const std::string& Direction_Name(T enum_t_value) {
  static_assert(::std::is_same<T, Direction>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function Direction_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    Direction_descriptor(), enum_t_value);
}
inline bool Direction_Parse(
    const std::string& name, Direction* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<Direction>(
    Direction_descriptor(), name, value);
}
enum ObjectType : int {
  OBJECT = 0,
  PLAYER = 1,
  INGREDIENT = 2,
  COOKWARE = 3,
  WALL = 4
};
bool ObjectType_IsValid(int value);
constexpr ObjectType ObjectType_MIN = OBJECT;
constexpr ObjectType ObjectType_MAX = WALL;
constexpr int ObjectType_ARRAYSIZE = ObjectType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ObjectType_descriptor();
template<typename T>
inline const std::string& ObjectType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, ObjectType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function ObjectType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    ObjectType_descriptor(), enum_t_value);
}
inline bool ObjectType_Parse(
    const std::string& name, ObjectType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<ObjectType>(
    ObjectType_descriptor(), name, value);
}
// ===================================================================

class ClientMessage :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Game.ClientMessage) */ {
 public:
  ClientMessage();
  virtual ~ClientMessage();

  ClientMessage(const ClientMessage& from);
  ClientMessage(ClientMessage&& from) noexcept
    : ClientMessage() {
    *this = ::std::move(from);
  }

  inline ClientMessage& operator=(const ClientMessage& from) {
    CopyFrom(from);
    return *this;
  }
  inline ClientMessage& operator=(ClientMessage&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const ClientMessage& default_instance();

  enum EventCase {
    kNet = 1,
    kDirection = 2,
    EVENT_NOT_SET = 0,
  };

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ClientMessage* internal_default_instance() {
    return reinterpret_cast<const ClientMessage*>(
               &_ClientMessage_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(ClientMessage& a, ClientMessage& b) {
    a.Swap(&b);
  }
  inline void Swap(ClientMessage* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline ClientMessage* New() const final {
    return CreateMaybeMessage<ClientMessage>(nullptr);
  }

  ClientMessage* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ClientMessage>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const ClientMessage& from);
  void MergeFrom(const ClientMessage& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ClientMessage* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Game.ClientMessage";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_Game_2eproto);
    return ::descriptor_table_Game_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNetFieldNumber = 1,
    kDirectionFieldNumber = 2,
  };
  // optional .Game.Net net = 1;
  bool has_net() const;
  private:
  bool _internal_has_net() const;
  public:
  void clear_net();
  ::Game::Net net() const;
  void set_net(::Game::Net value);
  private:
  ::Game::Net _internal_net() const;
  void _internal_set_net(::Game::Net value);
  public:

  // optional .Game.Direction direction = 2;
  bool has_direction() const;
  private:
  bool _internal_has_direction() const;
  public:
  void clear_direction();
  ::Game::Direction direction() const;
  void set_direction(::Game::Direction value);
  private:
  ::Game::Direction _internal_direction() const;
  void _internal_set_direction(::Game::Direction value);
  public:

  void clear_event();
  EventCase event_case() const;
  // @@protoc_insertion_point(class_scope:Game.ClientMessage)
 private:
  class _Internal;
  void set_has_net();
  void set_has_direction();

  inline bool has_event() const;
  inline void clear_has_event();

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  union EventUnion {
    EventUnion() {}
    int net_;
    int direction_;
  } event_;
  ::PROTOBUF_NAMESPACE_ID::uint32 _oneof_case_[1];

  friend struct ::TableStruct_Game_2eproto;
};
// -------------------------------------------------------------------

class ServerMessage :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Game.ServerMessage) */ {
 public:
  ServerMessage();
  virtual ~ServerMessage();

  ServerMessage(const ServerMessage& from);
  ServerMessage(ServerMessage&& from) noexcept
    : ServerMessage() {
    *this = ::std::move(from);
  }

  inline ServerMessage& operator=(const ServerMessage& from) {
    CopyFrom(from);
    return *this;
  }
  inline ServerMessage& operator=(ServerMessage&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const ServerMessage& default_instance();

  enum EventCase {
    kNet = 1,
    kObject = 2,
    kScore = 3,
    kInventory = 4,
    EVENT_NOT_SET = 0,
  };

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ServerMessage* internal_default_instance() {
    return reinterpret_cast<const ServerMessage*>(
               &_ServerMessage_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(ServerMessage& a, ServerMessage& b) {
    a.Swap(&b);
  }
  inline void Swap(ServerMessage* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline ServerMessage* New() const final {
    return CreateMaybeMessage<ServerMessage>(nullptr);
  }

  ServerMessage* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ServerMessage>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const ServerMessage& from);
  void MergeFrom(const ServerMessage& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ServerMessage* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Game.ServerMessage";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_Game_2eproto);
    return ::descriptor_table_Game_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNetFieldNumber = 1,
    kObjectFieldNumber = 2,
    kScoreFieldNumber = 3,
    kInventoryFieldNumber = 4,
  };
  // optional .Game.Net net = 1;
  bool has_net() const;
  private:
  bool _internal_has_net() const;
  public:
  void clear_net();
  ::Game::Net net() const;
  void set_net(::Game::Net value);
  private:
  ::Game::Net _internal_net() const;
  void _internal_set_net(::Game::Net value);
  public:

  // optional .Game.Object object = 2;
  bool has_object() const;
  private:
  bool _internal_has_object() const;
  public:
  void clear_object();
  const ::Game::Object& object() const;
  ::Game::Object* release_object();
  ::Game::Object* mutable_object();
  void set_allocated_object(::Game::Object* object);
  private:
  const ::Game::Object& _internal_object() const;
  ::Game::Object* _internal_mutable_object();
  public:

  // optional .Game.Score score = 3;
  bool has_score() const;
  private:
  bool _internal_has_score() const;
  public:
  void clear_score();
  const ::Game::Score& score() const;
  ::Game::Score* release_score();
  ::Game::Score* mutable_score();
  void set_allocated_score(::Game::Score* score);
  private:
  const ::Game::Score& _internal_score() const;
  ::Game::Score* _internal_mutable_score();
  public:

  // optional .Game.Inventory inventory = 4;
  bool has_inventory() const;
  private:
  bool _internal_has_inventory() const;
  public:
  void clear_inventory();
  const ::Game::Inventory& inventory() const;
  ::Game::Inventory* release_inventory();
  ::Game::Inventory* mutable_inventory();
  void set_allocated_inventory(::Game::Inventory* inventory);
  private:
  const ::Game::Inventory& _internal_inventory() const;
  ::Game::Inventory* _internal_mutable_inventory();
  public:

  void clear_event();
  EventCase event_case() const;
  // @@protoc_insertion_point(class_scope:Game.ServerMessage)
 private:
  class _Internal;
  void set_has_net();
  void set_has_object();
  void set_has_score();
  void set_has_inventory();

  inline bool has_event() const;
  inline void clear_has_event();

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  union EventUnion {
    EventUnion() {}
    int net_;
    ::Game::Object* object_;
    ::Game::Score* score_;
    ::Game::Inventory* inventory_;
  } event_;
  ::PROTOBUF_NAMESPACE_ID::uint32 _oneof_case_[1];

  friend struct ::TableStruct_Game_2eproto;
};
// -------------------------------------------------------------------

class Object :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Game.Object) */ {
 public:
  Object();
  virtual ~Object();

  Object(const Object& from);
  Object(Object&& from) noexcept
    : Object() {
    *this = ::std::move(from);
  }

  inline Object& operator=(const Object& from) {
    CopyFrom(from);
    return *this;
  }
  inline Object& operator=(Object&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Object& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Object* internal_default_instance() {
    return reinterpret_cast<const Object*>(
               &_Object_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(Object& a, Object& b) {
    a.Swap(&b);
  }
  inline void Swap(Object* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Object* New() const final {
    return CreateMaybeMessage<Object>(nullptr);
  }

  Object* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Object>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Object& from);
  void MergeFrom(const Object& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Object* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Game.Object";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_Game_2eproto);
    return ::descriptor_table_Game_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kModelPathFieldNumber = 6,
    kWorldPositionFieldNumber = 1,
    kRotationFieldNumber = 2,
    kIdFieldNumber = 3,
    kTypeFieldNumber = 4,
    kRenderFieldNumber = 5,
  };
  // required string modelPath = 6 [default = ""];
  bool has_modelpath() const;
  private:
  bool _internal_has_modelpath() const;
  public:
  void clear_modelpath();
  const std::string& modelpath() const;
  void set_modelpath(const std::string& value);
  void set_modelpath(std::string&& value);
  void set_modelpath(const char* value);
  void set_modelpath(const char* value, size_t size);
  std::string* mutable_modelpath();
  std::string* release_modelpath();
  void set_allocated_modelpath(std::string* modelpath);
  private:
  const std::string& _internal_modelpath() const;
  void _internal_set_modelpath(const std::string& value);
  std::string* _internal_mutable_modelpath();
  public:

  // required .Game.Vector3 worldPosition = 1;
  bool has_worldposition() const;
  private:
  bool _internal_has_worldposition() const;
  public:
  void clear_worldposition();
  const ::Game::Vector3& worldposition() const;
  ::Game::Vector3* release_worldposition();
  ::Game::Vector3* mutable_worldposition();
  void set_allocated_worldposition(::Game::Vector3* worldposition);
  private:
  const ::Game::Vector3& _internal_worldposition() const;
  ::Game::Vector3* _internal_mutable_worldposition();
  public:

  // required float rotation = 2;
  bool has_rotation() const;
  private:
  bool _internal_has_rotation() const;
  public:
  void clear_rotation();
  float rotation() const;
  void set_rotation(float value);
  private:
  float _internal_rotation() const;
  void _internal_set_rotation(float value);
  public:

  // required uint32 id = 3;
  bool has_id() const;
  private:
  bool _internal_has_id() const;
  public:
  void clear_id();
  ::PROTOBUF_NAMESPACE_ID::uint32 id() const;
  void set_id(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_id() const;
  void _internal_set_id(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // required .Game.ObjectType type = 4;
  bool has_type() const;
  private:
  bool _internal_has_type() const;
  public:
  void clear_type();
  ::Game::ObjectType type() const;
  void set_type(::Game::ObjectType value);
  private:
  ::Game::ObjectType _internal_type() const;
  void _internal_set_type(::Game::ObjectType value);
  public:

  // required bool render = 5 [default = true];
  bool has_render() const;
  private:
  bool _internal_has_render() const;
  public:
  void clear_render();
  bool render() const;
  void set_render(bool value);
  private:
  bool _internal_render() const;
  void _internal_set_render(bool value);
  public:

  // @@protoc_insertion_point(class_scope:Game.Object)
 private:
  class _Internal;

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr modelpath_;
  ::Game::Vector3* worldposition_;
  float rotation_;
  ::PROTOBUF_NAMESPACE_ID::uint32 id_;
  int type_;
  bool render_;
  friend struct ::TableStruct_Game_2eproto;
};
// -------------------------------------------------------------------

class Score :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Game.Score) */ {
 public:
  Score();
  virtual ~Score();

  Score(const Score& from);
  Score(Score&& from) noexcept
    : Score() {
    *this = ::std::move(from);
  }

  inline Score& operator=(const Score& from) {
    CopyFrom(from);
    return *this;
  }
  inline Score& operator=(Score&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Score& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Score* internal_default_instance() {
    return reinterpret_cast<const Score*>(
               &_Score_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(Score& a, Score& b) {
    a.Swap(&b);
  }
  inline void Swap(Score* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Score* New() const final {
    return CreateMaybeMessage<Score>(nullptr);
  }

  Score* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Score>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Score& from);
  void MergeFrom(const Score& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Score* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Game.Score";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_Game_2eproto);
    return ::descriptor_table_Game_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:Game.Score)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_Game_2eproto;
};
// -------------------------------------------------------------------

class Vector3 :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Game.Vector3) */ {
 public:
  Vector3();
  virtual ~Vector3();

  Vector3(const Vector3& from);
  Vector3(Vector3&& from) noexcept
    : Vector3() {
    *this = ::std::move(from);
  }

  inline Vector3& operator=(const Vector3& from) {
    CopyFrom(from);
    return *this;
  }
  inline Vector3& operator=(Vector3&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Vector3& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Vector3* internal_default_instance() {
    return reinterpret_cast<const Vector3*>(
               &_Vector3_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(Vector3& a, Vector3& b) {
    a.Swap(&b);
  }
  inline void Swap(Vector3* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Vector3* New() const final {
    return CreateMaybeMessage<Vector3>(nullptr);
  }

  Vector3* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Vector3>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Vector3& from);
  void MergeFrom(const Vector3& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Vector3* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Game.Vector3";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_Game_2eproto);
    return ::descriptor_table_Game_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kYFieldNumber = 2,
    kXFieldNumber = 1,
    kZFieldNumber = 3,
  };
  // required float y = 2 [default = 0];
  bool has_y() const;
  private:
  bool _internal_has_y() const;
  public:
  void clear_y();
  float y() const;
  void set_y(float value);
  private:
  float _internal_y() const;
  void _internal_set_y(float value);
  public:

  // required float x = 1 [default = 1];
  bool has_x() const;
  private:
  bool _internal_has_x() const;
  public:
  void clear_x();
  float x() const;
  void set_x(float value);
  private:
  float _internal_x() const;
  void _internal_set_x(float value);
  public:

  // required float z = 3 [default = 1];
  bool has_z() const;
  private:
  bool _internal_has_z() const;
  public:
  void clear_z();
  float z() const;
  void set_z(float value);
  private:
  float _internal_z() const;
  void _internal_set_z(float value);
  public:

  // @@protoc_insertion_point(class_scope:Game.Vector3)
 private:
  class _Internal;

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  float y_;
  float x_;
  float z_;
  friend struct ::TableStruct_Game_2eproto;
};
// -------------------------------------------------------------------

class Inventory :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Game.Inventory) */ {
 public:
  Inventory();
  virtual ~Inventory();

  Inventory(const Inventory& from);
  Inventory(Inventory&& from) noexcept
    : Inventory() {
    *this = ::std::move(from);
  }

  inline Inventory& operator=(const Inventory& from) {
    CopyFrom(from);
    return *this;
  }
  inline Inventory& operator=(Inventory&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Inventory& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Inventory* internal_default_instance() {
    return reinterpret_cast<const Inventory*>(
               &_Inventory_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(Inventory& a, Inventory& b) {
    a.Swap(&b);
  }
  inline void Swap(Inventory* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Inventory* New() const final {
    return CreateMaybeMessage<Inventory>(nullptr);
  }

  Inventory* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Inventory>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Inventory& from);
  void MergeFrom(const Inventory& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Inventory* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Game.Inventory";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_Game_2eproto);
    return ::descriptor_table_Game_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kIdFieldNumber = 1,
    kAddFieldNumber = 2,
  };
  // required uint32 id = 1;
  bool has_id() const;
  private:
  bool _internal_has_id() const;
  public:
  void clear_id();
  ::PROTOBUF_NAMESPACE_ID::uint32 id() const;
  void set_id(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_id() const;
  void _internal_set_id(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // required bool add = 2 [default = true];
  bool has_add() const;
  private:
  bool _internal_has_add() const;
  public:
  void clear_add();
  bool add() const;
  void set_add(bool value);
  private:
  bool _internal_add() const;
  void _internal_set_add(bool value);
  public:

  // @@protoc_insertion_point(class_scope:Game.Inventory)
 private:
  class _Internal;

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::uint32 id_;
  bool add_;
  friend struct ::TableStruct_Game_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ClientMessage

// optional .Game.Net net = 1;
inline bool ClientMessage::_internal_has_net() const {
  return event_case() == kNet;
}
inline bool ClientMessage::has_net() const {
  return _internal_has_net();
}
inline void ClientMessage::set_has_net() {
  _oneof_case_[0] = kNet;
}
inline void ClientMessage::clear_net() {
  if (_internal_has_net()) {
    event_.net_ = 0;
    clear_has_event();
  }
}
inline ::Game::Net ClientMessage::_internal_net() const {
  if (_internal_has_net()) {
    return static_cast< ::Game::Net >(event_.net_);
  }
  return static_cast< ::Game::Net >(0);
}
inline ::Game::Net ClientMessage::net() const {
  // @@protoc_insertion_point(field_get:Game.ClientMessage.net)
  return _internal_net();
}
inline void ClientMessage::_internal_set_net(::Game::Net value) {
  assert(::Game::Net_IsValid(value));
  if (!_internal_has_net()) {
    clear_event();
    set_has_net();
  }
  event_.net_ = value;
}
inline void ClientMessage::set_net(::Game::Net value) {
  // @@protoc_insertion_point(field_set:Game.ClientMessage.net)
  _internal_set_net(value);
}

// optional .Game.Direction direction = 2;
inline bool ClientMessage::_internal_has_direction() const {
  return event_case() == kDirection;
}
inline bool ClientMessage::has_direction() const {
  return _internal_has_direction();
}
inline void ClientMessage::set_has_direction() {
  _oneof_case_[0] = kDirection;
}
inline void ClientMessage::clear_direction() {
  if (_internal_has_direction()) {
    event_.direction_ = 0;
    clear_has_event();
  }
}
inline ::Game::Direction ClientMessage::_internal_direction() const {
  if (_internal_has_direction()) {
    return static_cast< ::Game::Direction >(event_.direction_);
  }
  return static_cast< ::Game::Direction >(0);
}
inline ::Game::Direction ClientMessage::direction() const {
  // @@protoc_insertion_point(field_get:Game.ClientMessage.direction)
  return _internal_direction();
}
inline void ClientMessage::_internal_set_direction(::Game::Direction value) {
  assert(::Game::Direction_IsValid(value));
  if (!_internal_has_direction()) {
    clear_event();
    set_has_direction();
  }
  event_.direction_ = value;
}
inline void ClientMessage::set_direction(::Game::Direction value) {
  // @@protoc_insertion_point(field_set:Game.ClientMessage.direction)
  _internal_set_direction(value);
}

inline bool ClientMessage::has_event() const {
  return event_case() != EVENT_NOT_SET;
}
inline void ClientMessage::clear_has_event() {
  _oneof_case_[0] = EVENT_NOT_SET;
}
inline ClientMessage::EventCase ClientMessage::event_case() const {
  return ClientMessage::EventCase(_oneof_case_[0]);
}
// -------------------------------------------------------------------

// ServerMessage

// optional .Game.Net net = 1;
inline bool ServerMessage::_internal_has_net() const {
  return event_case() == kNet;
}
inline bool ServerMessage::has_net() const {
  return _internal_has_net();
}
inline void ServerMessage::set_has_net() {
  _oneof_case_[0] = kNet;
}
inline void ServerMessage::clear_net() {
  if (_internal_has_net()) {
    event_.net_ = 0;
    clear_has_event();
  }
}
inline ::Game::Net ServerMessage::_internal_net() const {
  if (_internal_has_net()) {
    return static_cast< ::Game::Net >(event_.net_);
  }
  return static_cast< ::Game::Net >(0);
}
inline ::Game::Net ServerMessage::net() const {
  // @@protoc_insertion_point(field_get:Game.ServerMessage.net)
  return _internal_net();
}
inline void ServerMessage::_internal_set_net(::Game::Net value) {
  assert(::Game::Net_IsValid(value));
  if (!_internal_has_net()) {
    clear_event();
    set_has_net();
  }
  event_.net_ = value;
}
inline void ServerMessage::set_net(::Game::Net value) {
  // @@protoc_insertion_point(field_set:Game.ServerMessage.net)
  _internal_set_net(value);
}

// optional .Game.Object object = 2;
inline bool ServerMessage::_internal_has_object() const {
  return event_case() == kObject;
}
inline bool ServerMessage::has_object() const {
  return _internal_has_object();
}
inline void ServerMessage::set_has_object() {
  _oneof_case_[0] = kObject;
}
inline void ServerMessage::clear_object() {
  if (_internal_has_object()) {
    delete event_.object_;
    clear_has_event();
  }
}
inline ::Game::Object* ServerMessage::release_object() {
  // @@protoc_insertion_point(field_release:Game.ServerMessage.object)
  if (_internal_has_object()) {
    clear_has_event();
      ::Game::Object* temp = event_.object_;
    event_.object_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::Game::Object& ServerMessage::_internal_object() const {
  return _internal_has_object()
      ? *event_.object_
      : *reinterpret_cast< ::Game::Object*>(&::Game::_Object_default_instance_);
}
inline const ::Game::Object& ServerMessage::object() const {
  // @@protoc_insertion_point(field_get:Game.ServerMessage.object)
  return _internal_object();
}
inline ::Game::Object* ServerMessage::_internal_mutable_object() {
  if (!_internal_has_object()) {
    clear_event();
    set_has_object();
    event_.object_ = CreateMaybeMessage< ::Game::Object >(
        GetArenaNoVirtual());
  }
  return event_.object_;
}
inline ::Game::Object* ServerMessage::mutable_object() {
  // @@protoc_insertion_point(field_mutable:Game.ServerMessage.object)
  return _internal_mutable_object();
}

// optional .Game.Score score = 3;
inline bool ServerMessage::_internal_has_score() const {
  return event_case() == kScore;
}
inline bool ServerMessage::has_score() const {
  return _internal_has_score();
}
inline void ServerMessage::set_has_score() {
  _oneof_case_[0] = kScore;
}
inline void ServerMessage::clear_score() {
  if (_internal_has_score()) {
    delete event_.score_;
    clear_has_event();
  }
}
inline ::Game::Score* ServerMessage::release_score() {
  // @@protoc_insertion_point(field_release:Game.ServerMessage.score)
  if (_internal_has_score()) {
    clear_has_event();
      ::Game::Score* temp = event_.score_;
    event_.score_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::Game::Score& ServerMessage::_internal_score() const {
  return _internal_has_score()
      ? *event_.score_
      : *reinterpret_cast< ::Game::Score*>(&::Game::_Score_default_instance_);
}
inline const ::Game::Score& ServerMessage::score() const {
  // @@protoc_insertion_point(field_get:Game.ServerMessage.score)
  return _internal_score();
}
inline ::Game::Score* ServerMessage::_internal_mutable_score() {
  if (!_internal_has_score()) {
    clear_event();
    set_has_score();
    event_.score_ = CreateMaybeMessage< ::Game::Score >(
        GetArenaNoVirtual());
  }
  return event_.score_;
}
inline ::Game::Score* ServerMessage::mutable_score() {
  // @@protoc_insertion_point(field_mutable:Game.ServerMessage.score)
  return _internal_mutable_score();
}

// optional .Game.Inventory inventory = 4;
inline bool ServerMessage::_internal_has_inventory() const {
  return event_case() == kInventory;
}
inline bool ServerMessage::has_inventory() const {
  return _internal_has_inventory();
}
inline void ServerMessage::set_has_inventory() {
  _oneof_case_[0] = kInventory;
}
inline void ServerMessage::clear_inventory() {
  if (_internal_has_inventory()) {
    delete event_.inventory_;
    clear_has_event();
  }
}
inline ::Game::Inventory* ServerMessage::release_inventory() {
  // @@protoc_insertion_point(field_release:Game.ServerMessage.inventory)
  if (_internal_has_inventory()) {
    clear_has_event();
      ::Game::Inventory* temp = event_.inventory_;
    event_.inventory_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::Game::Inventory& ServerMessage::_internal_inventory() const {
  return _internal_has_inventory()
      ? *event_.inventory_
      : *reinterpret_cast< ::Game::Inventory*>(&::Game::_Inventory_default_instance_);
}
inline const ::Game::Inventory& ServerMessage::inventory() const {
  // @@protoc_insertion_point(field_get:Game.ServerMessage.inventory)
  return _internal_inventory();
}
inline ::Game::Inventory* ServerMessage::_internal_mutable_inventory() {
  if (!_internal_has_inventory()) {
    clear_event();
    set_has_inventory();
    event_.inventory_ = CreateMaybeMessage< ::Game::Inventory >(
        GetArenaNoVirtual());
  }
  return event_.inventory_;
}
inline ::Game::Inventory* ServerMessage::mutable_inventory() {
  // @@protoc_insertion_point(field_mutable:Game.ServerMessage.inventory)
  return _internal_mutable_inventory();
}

inline bool ServerMessage::has_event() const {
  return event_case() != EVENT_NOT_SET;
}
inline void ServerMessage::clear_has_event() {
  _oneof_case_[0] = EVENT_NOT_SET;
}
inline ServerMessage::EventCase ServerMessage::event_case() const {
  return ServerMessage::EventCase(_oneof_case_[0]);
}
// -------------------------------------------------------------------

// Object

// required .Game.Vector3 worldPosition = 1;
inline bool Object::_internal_has_worldposition() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  PROTOBUF_ASSUME(!value || worldposition_ != nullptr);
  return value;
}
inline bool Object::has_worldposition() const {
  return _internal_has_worldposition();
}
inline void Object::clear_worldposition() {
  if (worldposition_ != nullptr) worldposition_->Clear();
  _has_bits_[0] &= ~0x00000002u;
}
inline const ::Game::Vector3& Object::_internal_worldposition() const {
  const ::Game::Vector3* p = worldposition_;
  return p != nullptr ? *p : *reinterpret_cast<const ::Game::Vector3*>(
      &::Game::_Vector3_default_instance_);
}
inline const ::Game::Vector3& Object::worldposition() const {
  // @@protoc_insertion_point(field_get:Game.Object.worldPosition)
  return _internal_worldposition();
}
inline ::Game::Vector3* Object::release_worldposition() {
  // @@protoc_insertion_point(field_release:Game.Object.worldPosition)
  _has_bits_[0] &= ~0x00000002u;
  ::Game::Vector3* temp = worldposition_;
  worldposition_ = nullptr;
  return temp;
}
inline ::Game::Vector3* Object::_internal_mutable_worldposition() {
  _has_bits_[0] |= 0x00000002u;
  if (worldposition_ == nullptr) {
    auto* p = CreateMaybeMessage<::Game::Vector3>(GetArenaNoVirtual());
    worldposition_ = p;
  }
  return worldposition_;
}
inline ::Game::Vector3* Object::mutable_worldposition() {
  // @@protoc_insertion_point(field_mutable:Game.Object.worldPosition)
  return _internal_mutable_worldposition();
}
inline void Object::set_allocated_worldposition(::Game::Vector3* worldposition) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete worldposition_;
  }
  if (worldposition) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      worldposition = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, worldposition, submessage_arena);
    }
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  worldposition_ = worldposition;
  // @@protoc_insertion_point(field_set_allocated:Game.Object.worldPosition)
}

// required float rotation = 2;
inline bool Object::_internal_has_rotation() const {
  bool value = (_has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool Object::has_rotation() const {
  return _internal_has_rotation();
}
inline void Object::clear_rotation() {
  rotation_ = 0;
  _has_bits_[0] &= ~0x00000004u;
}
inline float Object::_internal_rotation() const {
  return rotation_;
}
inline float Object::rotation() const {
  // @@protoc_insertion_point(field_get:Game.Object.rotation)
  return _internal_rotation();
}
inline void Object::_internal_set_rotation(float value) {
  _has_bits_[0] |= 0x00000004u;
  rotation_ = value;
}
inline void Object::set_rotation(float value) {
  _internal_set_rotation(value);
  // @@protoc_insertion_point(field_set:Game.Object.rotation)
}

// required uint32 id = 3;
inline bool Object::_internal_has_id() const {
  bool value = (_has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline bool Object::has_id() const {
  return _internal_has_id();
}
inline void Object::clear_id() {
  id_ = 0u;
  _has_bits_[0] &= ~0x00000008u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 Object::_internal_id() const {
  return id_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 Object::id() const {
  // @@protoc_insertion_point(field_get:Game.Object.id)
  return _internal_id();
}
inline void Object::_internal_set_id(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _has_bits_[0] |= 0x00000008u;
  id_ = value;
}
inline void Object::set_id(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_id(value);
  // @@protoc_insertion_point(field_set:Game.Object.id)
}

// required .Game.ObjectType type = 4;
inline bool Object::_internal_has_type() const {
  bool value = (_has_bits_[0] & 0x00000010u) != 0;
  return value;
}
inline bool Object::has_type() const {
  return _internal_has_type();
}
inline void Object::clear_type() {
  type_ = 0;
  _has_bits_[0] &= ~0x00000010u;
}
inline ::Game::ObjectType Object::_internal_type() const {
  return static_cast< ::Game::ObjectType >(type_);
}
inline ::Game::ObjectType Object::type() const {
  // @@protoc_insertion_point(field_get:Game.Object.type)
  return _internal_type();
}
inline void Object::_internal_set_type(::Game::ObjectType value) {
  assert(::Game::ObjectType_IsValid(value));
  _has_bits_[0] |= 0x00000010u;
  type_ = value;
}
inline void Object::set_type(::Game::ObjectType value) {
  _internal_set_type(value);
  // @@protoc_insertion_point(field_set:Game.Object.type)
}

// required bool render = 5 [default = true];
inline bool Object::_internal_has_render() const {
  bool value = (_has_bits_[0] & 0x00000020u) != 0;
  return value;
}
inline bool Object::has_render() const {
  return _internal_has_render();
}
inline void Object::clear_render() {
  render_ = true;
  _has_bits_[0] &= ~0x00000020u;
}
inline bool Object::_internal_render() const {
  return render_;
}
inline bool Object::render() const {
  // @@protoc_insertion_point(field_get:Game.Object.render)
  return _internal_render();
}
inline void Object::_internal_set_render(bool value) {
  _has_bits_[0] |= 0x00000020u;
  render_ = value;
}
inline void Object::set_render(bool value) {
  _internal_set_render(value);
  // @@protoc_insertion_point(field_set:Game.Object.render)
}

// required string modelPath = 6 [default = ""];
inline bool Object::_internal_has_modelpath() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool Object::has_modelpath() const {
  return _internal_has_modelpath();
}
inline void Object::clear_modelpath() {
  modelpath_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& Object::modelpath() const {
  // @@protoc_insertion_point(field_get:Game.Object.modelPath)
  return _internal_modelpath();
}
inline void Object::set_modelpath(const std::string& value) {
  _internal_set_modelpath(value);
  // @@protoc_insertion_point(field_set:Game.Object.modelPath)
}
inline std::string* Object::mutable_modelpath() {
  // @@protoc_insertion_point(field_mutable:Game.Object.modelPath)
  return _internal_mutable_modelpath();
}
inline const std::string& Object::_internal_modelpath() const {
  return modelpath_.GetNoArena();
}
inline void Object::_internal_set_modelpath(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  modelpath_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void Object::set_modelpath(std::string&& value) {
  _has_bits_[0] |= 0x00000001u;
  modelpath_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Game.Object.modelPath)
}
inline void Object::set_modelpath(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000001u;
  modelpath_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Game.Object.modelPath)
}
inline void Object::set_modelpath(const char* value, size_t size) {
  _has_bits_[0] |= 0x00000001u;
  modelpath_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Game.Object.modelPath)
}
inline std::string* Object::_internal_mutable_modelpath() {
  _has_bits_[0] |= 0x00000001u;
  return modelpath_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* Object::release_modelpath() {
  // @@protoc_insertion_point(field_release:Game.Object.modelPath)
  if (!_internal_has_modelpath()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return modelpath_.ReleaseNonDefaultNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void Object::set_allocated_modelpath(std::string* modelpath) {
  if (modelpath != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  modelpath_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), modelpath);
  // @@protoc_insertion_point(field_set_allocated:Game.Object.modelPath)
}

// -------------------------------------------------------------------

// Score

// -------------------------------------------------------------------

// Vector3

// required float x = 1 [default = 1];
inline bool Vector3::_internal_has_x() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool Vector3::has_x() const {
  return _internal_has_x();
}
inline void Vector3::clear_x() {
  x_ = 1;
  _has_bits_[0] &= ~0x00000002u;
}
inline float Vector3::_internal_x() const {
  return x_;
}
inline float Vector3::x() const {
  // @@protoc_insertion_point(field_get:Game.Vector3.x)
  return _internal_x();
}
inline void Vector3::_internal_set_x(float value) {
  _has_bits_[0] |= 0x00000002u;
  x_ = value;
}
inline void Vector3::set_x(float value) {
  _internal_set_x(value);
  // @@protoc_insertion_point(field_set:Game.Vector3.x)
}

// required float y = 2 [default = 0];
inline bool Vector3::_internal_has_y() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool Vector3::has_y() const {
  return _internal_has_y();
}
inline void Vector3::clear_y() {
  y_ = 0;
  _has_bits_[0] &= ~0x00000001u;
}
inline float Vector3::_internal_y() const {
  return y_;
}
inline float Vector3::y() const {
  // @@protoc_insertion_point(field_get:Game.Vector3.y)
  return _internal_y();
}
inline void Vector3::_internal_set_y(float value) {
  _has_bits_[0] |= 0x00000001u;
  y_ = value;
}
inline void Vector3::set_y(float value) {
  _internal_set_y(value);
  // @@protoc_insertion_point(field_set:Game.Vector3.y)
}

// required float z = 3 [default = 1];
inline bool Vector3::_internal_has_z() const {
  bool value = (_has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool Vector3::has_z() const {
  return _internal_has_z();
}
inline void Vector3::clear_z() {
  z_ = 1;
  _has_bits_[0] &= ~0x00000004u;
}
inline float Vector3::_internal_z() const {
  return z_;
}
inline float Vector3::z() const {
  // @@protoc_insertion_point(field_get:Game.Vector3.z)
  return _internal_z();
}
inline void Vector3::_internal_set_z(float value) {
  _has_bits_[0] |= 0x00000004u;
  z_ = value;
}
inline void Vector3::set_z(float value) {
  _internal_set_z(value);
  // @@protoc_insertion_point(field_set:Game.Vector3.z)
}

// -------------------------------------------------------------------

// Inventory

// required uint32 id = 1;
inline bool Inventory::_internal_has_id() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool Inventory::has_id() const {
  return _internal_has_id();
}
inline void Inventory::clear_id() {
  id_ = 0u;
  _has_bits_[0] &= ~0x00000001u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 Inventory::_internal_id() const {
  return id_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 Inventory::id() const {
  // @@protoc_insertion_point(field_get:Game.Inventory.id)
  return _internal_id();
}
inline void Inventory::_internal_set_id(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _has_bits_[0] |= 0x00000001u;
  id_ = value;
}
inline void Inventory::set_id(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_id(value);
  // @@protoc_insertion_point(field_set:Game.Inventory.id)
}

// required bool add = 2 [default = true];
inline bool Inventory::_internal_has_add() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool Inventory::has_add() const {
  return _internal_has_add();
}
inline void Inventory::clear_add() {
  add_ = true;
  _has_bits_[0] &= ~0x00000002u;
}
inline bool Inventory::_internal_add() const {
  return add_;
}
inline bool Inventory::add() const {
  // @@protoc_insertion_point(field_get:Game.Inventory.add)
  return _internal_add();
}
inline void Inventory::_internal_set_add(bool value) {
  _has_bits_[0] |= 0x00000002u;
  add_ = value;
}
inline void Inventory::set_add(bool value) {
  _internal_set_add(value);
  // @@protoc_insertion_point(field_set:Game.Inventory.add)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace Game

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::Game::Net> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Game::Net>() {
  return ::Game::Net_descriptor();
}
template <> struct is_proto_enum< ::Game::Direction> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Game::Direction>() {
  return ::Game::Direction_descriptor();
}
template <> struct is_proto_enum< ::Game::ObjectType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Game::ObjectType>() {
  return ::Game::ObjectType_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_Game_2eproto
